killbill/killbill-analytics-plugin

src/main/resources/reports/payment_provider_conversion/README.md, src/main/resources/reports/payment_provider_conversion/v_report_payment_provider_conversion.ddl, src/main/resources/reports/payment_provider_conversion/v_report_payment_provider_conversion_sub1.ddl
=> Add Payment Provider Conversion report

src/main/resources/org/killbill/billing/plugin/analytics/ddl.sql
=> update ddl: change plugin_gateway_error type to text

src/main/java/org/killbill/billing/plugin/analytics/api/BusinessAccount.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessAccountFactory.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessContextFactory.java, src/main/java/org/killbill/billing/plugin/analytics/dao/model/BusinessAccountModelDao.java, src/main/resources/migration/V20170208000000__add_parent_account.sql, src/main/resources/org/killbill/billing/plugin/analytics/dao/BusinessAnalyticsSqlDao.sql.stg, src/main/resources/org/killbill/billing/plugin/analytics/ddl.sql, src/test/java/org/killbill/billing/plugin/analytics/AnalyticsTestSuiteNoDB.java, src/test/java/org/killbill/billing/plugin/analytics/api/TestBusinessAccount.java, src/test/java/org/killbill/billing/plugin/analytics/api/TestBusinessSnapshot.java, src/test/java/org/killbill/billing/plugin/analytics/api/user/TestDefaultAnalyticsUserApi.java, src/test/java/org/killbill/billing/plugin/analytics/dao/TestAnalyticsDao.java, src/test/java/org/killbill/billing/plugin/analytics/dao/TestBusinessAnalyticsSqlDao.java, src/test/java/org/killbill/billing/plugin/analytics/dao/model/TestBusinessAccountModelDao.java
I added the parent account id, parent account name, and parent account external key to the analytics_accounts table so that it can be used in reporting.  Please let me know if any changes are needed.  Thanks! 😀
=> Add parent account fields to analytics_accounts.

src/main/java/org/killbill/billing/plugin/analytics/AnalyticsListener.java, src/main/java/org/killbill/billing/plugin/analytics/api/user/AnalyticsUserApi.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessContextFactory.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessFactoryBase.java, src/test/java/org/killbill/billing/plugin/analytics/dao/factory/TestBusinessAccountTransitionFactory.java, src/test/java/org/killbill/billing/plugin/analytics/dao/factory/TestBusinessSubscriptionTransitionFactory.java
=> Remove use of logService for BusinessContextFactory

NEWS, pom.xml, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessContextFactory.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessFactoryBase.java
The catalog was pulled between 2 and 4 times for each invoice item record.
=> performance: cache catalog information

src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessContextFactory.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessFactoryBase.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessInvoiceFactory.java
See https://github.com/killbill/killbill/issues/784.
=> factory: fix catalog APIs invocation

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/compiler.xml, .idea/inspectionProfiles/Project_Default.xml, NEWS, src/main/java/org/killbill/billing/plugin/analytics/AnalyticsListener.java, src/test/java/org/killbill/billing/plugin/analytics/TestAnalyticsListener.java
This fixes https://github.com/killbill/killbill-analytics-plugin/issues/87.
/cc @beccagaspard
=> Add config option to ignore specific refresh groups

src/main/java/org/killbill/billing/plugin/analytics/dao/model/BusinessBundleModelDao.java, src/test/java/org/killbill/billing/plugin/analytics/dao/factory/TestBusinessBundleFactory.java, src/test/java/org/killbill/billing/plugin/analytics/dao/model/TestBusinessSubscription.java
This fixes https://github.com/killbill/killbill-analytics-plugin/issues/89.
=> bundle: populate current_end_date for cancelled subscriptions

src/main/java/org/killbill/billing/plugin/analytics/BusinessExecutor.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessContextFactory.java
This fixes https://github.com/killbill/killbill-analytics-plugin/issues/96.
Note: this is done on top of https://github.com/killbill/killbill-analytics-plugin/pull/95 to simplify the merge.
=> factory: improve synchronization

src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessTagFactory.java
This fixes https://github.com/killbill/killbill-analytics-plugin/issues/100.
=> factory: fix NPE in BusinessTagDao

.idea/inspectionProfiles/profiles_settings.xml, pom.xml, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessContextFactory.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessFactoryBase.java, src/test/java/org/killbill/billing/plugin/analytics/AnalyticsTestSuiteNoDB.java
⚠️ https://github.com/killbill/killbill-plugin-framework-java/pull/33 should be released first (and the pom.xml here updated).
Also, what is the status of https://github.com/killbill/killbill-analytics-plugin/pull/102?
=> pom.xml: update to killbill-oss-parent 0.143.34

src/main/resources/reports/v_report_invoice_item_credits_daily.ddl
In the `analytics_reports` table, this report is referred by this name.
=> Fixed report view name

README.md, pom.xml, src/main/java/org/killbill/billing/plugin/analytics/AnalyticsActivator.java, src/main/java/org/killbill/billing/plugin/analytics/api/core/AnalyticsConfiguration.java, src/main/java/org/killbill/billing/plugin/analytics/api/core/AnalyticsConfigurationHandler.java, src/main/java/org/killbill/billing/plugin/analytics/http/ObjectMapperProvider.java, src/main/java/org/killbill/billing/plugin/analytics/json/ReportConfigurationJson.java, src/main/java/org/killbill/billing/plugin/analytics/reports/QueryEngine.java, src/main/java/org/killbill/billing/plugin/analytics/reports/ReportsConfiguration.java, src/main/java/org/killbill/billing/plugin/analytics/reports/ReportsUserApi.java, src/main/java/org/killbill/billing/plugin/analytics/reports/configuration/ReportsConfigurationModelDao.java, src/main/java/org/killbill/billing/plugin/analytics/reports/databases/Trino.java, src/main/java/org/killbill/billing/plugin/analytics/reports/sql/Metadata.java, src/main/resources/migration/V20210405133036__add_source_name_source_query_to_analytics_reports.sql, src/main/resources/org/killbill/billing/plugin/analytics/ddl.sql, src/main/resources/org/killbill/billing/plugin/analytics/reports/configuration/ReportsConfigurationSqlDao.sql.stg, src/test/java/org/killbill/billing/plugin/analytics/AnalyticsTestSuiteNoDB.java, src/test/java/org/killbill/billing/plugin/analytics/reports/TestReportsConfiguration.java, src/test/java/org/killbill/billing/plugin/analytics/reports/configuration/TestReportsConfigurationModelDao.java, src/test/java/org/killbill/billing/plugin/analytics/reports/scheduler/TestJobsSchedulerWithEmbeddedDB.java
Notes:
* This introduces a DDL change in `analytics_reports`.
* Configuration has changed to a YAML format.
Hence, the 7.2.0 bump.
=> Initial Trino support

NEWS, src/main/java/org/killbill/billing/plugin/analytics/http/ReportsResource.java, src/test/java/org/killbill/billing/plugin/analytics/http/TestReportsServlet.java
Work around https://github.com/FasterXML/jackson-dataformats-text/issues/10.
=> csv: fix NULL handling

.github/workflows/ci.yml, NEWS, pom.xml
This adds support for Java 11.
=> pom.xml: update to killbill-oss-parent 0.144.58

pom.xml, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessContextFactory.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessFactoryBase.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/SafeAccountAuditLogs.java
Attempt to fix an old issue where analytics plugin complains it is missing some audit logs - this is untested code, so it may or not really fix the underlying issue.
=> Audit logs fix

src/main/java/org/killbill/billing/plugin/analytics/AnalyticsActivator.java, src/main/java/org/killbill/billing/plugin/analytics/AnalyticsListener.java, src/main/java/org/killbill/billing/plugin/analytics/api/RefreshResult.java, src/main/java/org/killbill/billing/plugin/analytics/api/user/AnalyticsUserApi.java, src/main/java/org/killbill/billing/plugin/analytics/http/AnalyticsAccountResource.java, src/main/java/org/killbill/billing/plugin/analytics/http/ReportsResource.java, src/test/java/org/killbill/billing/plugin/analytics/AnalyticsTestSuiteWithEmbeddedDB.java, src/test/java/org/killbill/billing/plugin/analytics/api/user/TestDefaultAnalyticsUserApi.java
Includes fix for refreshReport and added new endpoint for refresh all accounts as per t[his issue](https://github.com/killbill/technical-support/issues/45).
=> Fix for refreshReport and new endpoint for refreshAllAccounts

src/main/java/org/killbill/billing/plugin/analytics/dao/BusinessSubscriptionTransitionDao.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessAccountFactory.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessAccountTransitionFactory.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessContextFactory.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessFactoryBase.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/FixedSizeMap.java, src/main/java/org/killbill/billing/plugin/analytics/dao/factory/SafeAccountAuditLogs.java, src/test/java/org/killbill/billing/plugin/analytics/AnalyticsTestSuiteNoDB.java, src/test/java/org/killbill/billing/plugin/analytics/dao/factory/TestBusinessAccountTransitionFactory.java
Released `7.2.8-6909115` so we can try it out.
=> audit: avoid fetching all records for high cardinality accounts

pom.xml, src/main/resources/org/killbill/billing/plugin/analytics/ddl.sql
=> update version/parent version in pom and minor improvement to DDL

.github/workflows/release.yml, pom.xml, src/main/java/org/killbill/billing/plugin/analytics/AnalyticsActivator.java, src/test/java/org/killbill/billing/plugin/analytics/AnalyticsTestSuiteWithEmbeddedDB.java
- Changes for OSSRH migration
- Updated to parent pom 0.146.63
- Changes for AugmentedConfigurationObjectFactory
=> Changes for ossrh migration/AugmentedConfigurationObjectFactory
